Repository etalab/transport-ops, pull requests merged in 2018-03, with the labels that each got.

#1 Docker compose
  README.md
  datatools/Dockerfile
  datatools/env.yml
  datatools/server.yml
  docker-compose.yml
Labels: flow:in-progress

#2 Add transport site Dockerfile
  transport-site/Dockerfile
Labels: flow:in-progress, work:ops

#3 Update Readme for transport-site CI
  README.md
Labels: flow:in-progress, work:documentation

#4 Remove mongo and phantomjs from transport-site
  transport-site/Dockerfile
Labels: flow:in-progress, work:ops

#5 Update env.yml
  datatools/Dockerfile
  datatools/env.yml
Labels: flow:in-progress, work:ops
